/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/degenBox_box.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/degenBox_box.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box_Material001_0.geometry} material={nodes.Box_Material001_0.material} position={[0, 0.195, -0.94]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/degenBox_box.glb')
