/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Floor.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Floor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor_Baked.geometry} material={nodes.Floor_Baked.material} />
    </group>
  )
}

useGLTF.preload('/Floor.glb')
