/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vendingMachine.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vendingMachine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.vm_body_Baked.geometry} material={materials['vm_body_Baked.002']} />
      <mesh geometry={nodes.vm_parts_Baked.geometry} material={materials['vm_parts_Baked.002']} />
    </group>
  )
}

useGLTF.preload('/vendingMachine.glb')
