/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vendingMachine.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vendingMachine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.beverages_Baked.geometry} material={materials.beverages_Baked} />
      <mesh geometry={nodes.vm_ads_Baked.geometry} material={materials.vm_ads_Baked} />
      <mesh geometry={nodes.vm_body_Baked.geometry} material={materials.vm_body_Baked} />
      <mesh geometry={nodes.vm_parts_Baked.geometry} material={materials.vm_parts_Baked} />
    </group>
  )
}

useGLTF.preload('/vendingMachine.glb')
