// routes/projects.js
// API routes for project management

import express from 'express';
import { PublicKey } from '@solana/web3.js';
import { createClient } from '@supabase/supabase-js';
import { getNetworkConfig } from '../lib/getNetworkConfig.js';
import { deriveAllVaultAddresses } from '../lib/deriveVaultPDAs.js';

const router = express.Router();

// Initialize Supabase client
const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY
);

/**
 * POST /api/projects/create
 * Create a new project with vault PDAs
 *
 * Body:
 * - owner_wallet: string (creator's wallet address)
 * - project_name: string
 * - subdomain: string
 * - description: string (optional)
 * - payment_token_mint: string (SPL token address)
 * - box_price: number (in lamports)
 */
router.post('/create', async (req, res) => {
    try {
        const {
            owner_wallet,
            project_name,
            subdomain,
            description,
            payment_token_mint,
            box_price
        } = req.body;

        // Validate required fields
        if (!owner_wallet || !project_name || !subdomain || !payment_token_mint || !box_price) {
            return res.status(400).json({
                success: false,
                error: 'Missing required fields',
                required: ['owner_wallet', 'project_name', 'subdomain', 'payment_token_mint', 'box_price']
            });
        }

        // Validate wallet addresses
        try {
            new PublicKey(owner_wallet);
            new PublicKey(payment_token_mint);
        } catch (error) {
            return res.status(400).json({
                success: false,
                error: 'Invalid wallet address format'
            });
        }

        // Get network configuration
        const config = await getNetworkConfig();

        // Generate full subdomain with network prefix if devnet
        const fullSubdomain = config.network === 'devnet'
            ? `devnet-${subdomain}`
            : subdomain;

        // Check subdomain availability
        const { data: existingProject } = await supabase
            .from('projects')
            .select('id')
            .eq('subdomain', fullSubdomain)
            .single();

        if (existingProject) {
            return res.status(409).json({
                success: false,
                error: 'Subdomain already taken',
                subdomain: fullSubdomain
            });
        }

        // Generate unique project ID (UUID will be auto-generated by DB)
        // For PDA derivation, we'll use the UUID after insert
        // For now, use timestamp as temporary ID for PDA calculation
        const tempProjectId = Date.now().toString();

        // Derive vault PDAs
        console.log('Deriving vault PDAs for project:', tempProjectId);
        const paymentTokenPubkey = new PublicKey(payment_token_mint);
        const vaultAddresses = await deriveAllVaultAddresses(
            config.programId,
            tempProjectId,
            paymentTokenPubkey
        );

        console.log('Vault addresses derived:', {
            vaultPda: vaultAddresses.vaultPda,
            vaultAuthorityPda: vaultAddresses.vaultAuthorityPda,
            vaultTokenAccount: vaultAddresses.vaultTokenAccount
        });

        // Insert project into database
        const { data: project, error: insertError } = await supabase
            .from('projects')
            .insert({
                owner_wallet,
                project_name,
                subdomain: fullSubdomain,
                description: description || null,
                vault_wallet: vaultAddresses.vaultPda, // Main vault address
                vault_pda: vaultAddresses.vaultPda,
                vault_authority_pda: vaultAddresses.vaultAuthorityPda,
                vault_token_account: vaultAddresses.vaultTokenAccount,
                box_price: parseInt(box_price),
                max_boxes: 1000, // Default
                is_active: true,
                is_paused: false
            })
            .select()
            .single();

        if (insertError) {
            console.error('Database insert error:', insertError);
            return res.status(500).json({
                success: false,
                error: 'Failed to create project in database',
                details: insertError.message
            });
        }

        // Success response
        return res.status(201).json({
            success: true,
            project: {
                id: project.id,
                project_name: project.project_name,
                subdomain: project.subdomain,
                vault_addresses: {
                    vault_pda: vaultAddresses.vaultPda,
                    vault_authority_pda: vaultAddresses.vaultAuthorityPda,
                    vault_token_account: vaultAddresses.vaultTokenAccount
                },
                network: config.network,
                url: `https://${project.subdomain}.degenbox.fun`
            },
            message: 'Project created successfully! Vault PDAs derived and stored.'
        });

    } catch (error) {
        console.error('Error creating project:', error);
        return res.status(500).json({
            success: false,
            error: 'Internal server error',
            details: error.message
        });
    }
});

/**
 * GET /api/projects/:projectId
 * Get project details by ID
 */
router.get('/:projectId', async (req, res) => {
    try {
        const { projectId } = req.params;

        const { data: project, error } = await supabase
            .from('projects')
            .select('*')
            .eq('id', projectId)
            .single();

        if (error || !project) {
            return res.status(404).json({
                success: false,
                error: 'Project not found'
            });
        }

        return res.json({
            success: true,
            project
        });

    } catch (error) {
        console.error('Error fetching project:', error);
        return res.status(500).json({
            success: false,
            error: 'Internal server error',
            details: error.message
        });
    }
});

/**
 * GET /api/projects
 * List all active projects (filtered by current network)
 */
router.get('/', async (req, res) => {
    try {
        const config = await getNetworkConfig();

        // Get projects from current network only
        const { data: projects, error } = await supabase
            .from('projects')
            .select('*')
            .eq('is_active', true)
            .eq('archived', false)
            .order('created_at', { ascending: false });

        if (error) {
            throw error;
        }

        return res.json({
            success: true,
            network: config.network,
            count: projects.length,
            projects
        });

    } catch (error) {
        console.error('Error listing projects:', error);
        return res.status(500).json({
            success: false,
            error: 'Internal server error',
            details: error.message
        });
    }
});

export default router;
