-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_type character varying NOT NULL,
  event_category character varying NOT NULL,
  severity character varying NOT NULL DEFAULT 'info'::character varying CHECK (severity::text = ANY (ARRAY['debug'::character varying, 'info'::character varying, 'warning'::character varying, 'error'::character varying, 'critical'::character varying]::text[])),
  actor_type character varying NOT NULL CHECK (actor_type::text = ANY (ARRAY['user'::character varying, 'creator'::character varying, 'admin'::character varying, 'system'::character varying]::text[])),
  actor_wallet character varying,
  actor_id uuid,
  project_id bigint,
  project_subdomain character varying,
  box_id bigint,
  transaction_signature character varying,
  transaction_status character varying,
  amount_lamports bigint,
  amount_tokens bigint,
  token_mint character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  error_code character varying,
  error_message text,
  request_id uuid,
  ip_address inet,
  user_agent text,
  processed boolean DEFAULT false,
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.boxes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  box_number integer NOT NULL,
  project_id uuid NOT NULL,
  owner_wallet text NOT NULL,
  box_result integer DEFAULT 0 CHECK (box_result >= 0 AND box_result <= 6),
  payout_amount bigint DEFAULT 0,
  opened_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  settled_at timestamp with time zone,
  randomness_account text,
  randomness_committed boolean DEFAULT false,
  purchase_tx_signature text,
  reveal_tx_signature text,
  settle_tx_signature text,
  box_pda text,
  luck_value bigint,
  max_luck bigint,
  random_percentage numeric,
  committed_at timestamp with time zone,
  commit_tx_signature text,
  reveal_failed_at timestamp without time zone,
  reveal_failure_reason text,
  refund_eligible boolean DEFAULT false,
  refunded_at timestamp without time zone,
  refund_tx_signature text,
  randomness_closed boolean DEFAULT false,
  badge_image_id integer,
  CONSTRAINT boxes_pkey PRIMARY KEY (id),
  CONSTRAINT boxes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.log_aggregates (
  id integer NOT NULL DEFAULT nextval('log_aggregates_id_seq'::regclass),
  time_bucket timestamp with time zone NOT NULL,
  bucket_type character varying NOT NULL DEFAULT 'hourly'::character varying,
  event_category character varying,
  project_id bigint,
  total_events integer DEFAULT 0,
  info_count integer DEFAULT 0,
  warning_count integer DEFAULT 0,
  error_count integer DEFAULT 0,
  critical_count integer DEFAULT 0,
  total_lamports bigint DEFAULT 0,
  total_tokens bigint DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT log_aggregates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_counter (
  id integer NOT NULL DEFAULT 1,
  counter bigint DEFAULT 1,
  CONSTRAINT project_counter_pkey PRIMARY KEY (id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_name text NOT NULL,
  subdomain text NOT NULL UNIQUE CHECK (subdomain ~ '^[a-z0-9-]+$'::text),
  description text,
  owner_wallet text NOT NULL,
  vault_wallet text NOT NULL,
  box_price bigint NOT NULL CHECK (box_price > 0),
  max_boxes integer NOT NULL DEFAULT 1000 CHECK (max_boxes > 0),
  boxes_created integer DEFAULT 0,
  is_active boolean DEFAULT true,
  is_paused boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  launch_date timestamp without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  archived boolean DEFAULT false,
  vault_pda text,
  vault_authority_pda text,
  vault_token_account text,
  project_numeric_id bigint NOT NULL UNIQUE,
  payment_token_mint text,
  payment_token_symbol text,
  payment_token_decimals integer DEFAULT 9,
  network text DEFAULT 'devnet'::text,
  vault_funded boolean DEFAULT false,
  vault_funded_amount bigint,
  vault_funded_at timestamp without time zone,
  initial_vault_amount bigint DEFAULT 0,
  total_withdrawn bigint DEFAULT 0,
  last_withdrawal_at timestamp without time zone,
  launch_fee_paid_amount bigint DEFAULT 0,
  closing_at timestamp without time zone,
  closed_at timestamp without time zone,
  luck_interval_seconds integer,
  CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reserved_subdomains (
  subdomain text NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reserved_subdomains_pkey PRIMARY KEY (subdomain)
);
CREATE TABLE public.super_admin_config (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  network text NOT NULL DEFAULT 'devnet'::text,
  rpc_url text NOT NULL DEFAULT 'https://api.devnet.solana.com'::text,
  lootbox_program_id text NOT NULL DEFAULT '11111111111111111111111111111111'::text,
  three_eyes_mint text NOT NULL DEFAULT '11111111111111111111111111112222'::text,
  admin_wallet text NOT NULL,
  platform_fee_account text NOT NULL,
  launch_fee_amount bigint NOT NULL DEFAULT 1000000000,
  platform_active boolean DEFAULT true,
  maintenance_mode boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  luck_interval_seconds integer NOT NULL DEFAULT 3,
  platform_commission_bps integer NOT NULL DEFAULT 500,
  dev_cut_bps integer NOT NULL DEFAULT 1000,
  dev_wallet text,
  treasury_pda text,
  CONSTRAINT super_admin_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_health_logs (
  id integer NOT NULL DEFAULT nextval('system_health_logs_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metric_name character varying NOT NULL,
  metric_value numeric NOT NULL,
  metric_unit character varying,
  service character varying,
  environment character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT system_health_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.treasury_processing_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processed_at timestamp without time zone NOT NULL DEFAULT now(),
  processed_by text NOT NULL,
  action_type text NOT NULL DEFAULT 'withdraw'::text,
  token_mint text NOT NULL,
  token_amount bigint,
  amount_withdrawn bigint,
  sol_received bigint DEFAULT 0,
  dev_sol_amount bigint DEFAULT 0,
  buyback_sol_amount bigint DEFAULT 0,
  three_eyes_bought bigint DEFAULT 0,
  tx_signature text,
  swap_to_sol_signature text,
  dev_transfer_signature text,
  buyback_signature text,
  status text NOT NULL DEFAULT 'completed'::text,
  error_message text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT treasury_processing_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_address text NOT NULL,
  badge_type text NOT NULL CHECK (badge_type = ANY (ARRAY['jackpot'::text, 'creator'::text, 'boxes_10'::text, 'boxes_25'::text, 'boxes_50'::text, 'boxes_100'::text])),
  earned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_wallet_address_fkey FOREIGN KEY (wallet_address) REFERENCES public.user_profiles(wallet_address)
);
CREATE TABLE public.user_profiles (
  wallet_address text NOT NULL,
  username text UNIQUE CHECK (username IS NULL OR username ~ '^[a-z0-9_]{3,20}$'::text),
  x_handle text CHECK (x_handle IS NULL OR x_handle ~ '^[a-zA-Z0-9_]{1,15}$'::text),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (wallet_address)
);
CREATE TABLE public.withdrawal_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  owner_wallet text NOT NULL,
  withdrawal_amount bigint NOT NULL,
  withdrawal_type text NOT NULL CHECK (withdrawal_type = ANY (ARRAY['profits'::text, 'partial'::text, 'full_close'::text])),
  fee_percentage numeric NOT NULL,
  fee_amount_in_project_token bigint NOT NULL,
  fee_amount_in_platform_token bigint NOT NULL,
  project_token_price_usd numeric,
  platform_token_price_usd numeric,
  exchange_rate numeric,
  withdrawal_tx_signature text,
  fee_tx_signature text,
  vault_balance_before bigint NOT NULL,
  vault_balance_after bigint NOT NULL,
  reserved_for_boxes bigint NOT NULL,
  unopened_boxes_count integer NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  confirmed_at timestamp without time zone,
  CONSTRAINT withdrawal_history_pkey PRIMARY KEY (id),
  CONSTRAINT withdrawal_history_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);