/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vendingMachine.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function DegenBoxLogo(props) {
    const { nodes } = useGLTF('/models/degenboxLogo.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.DegenBoxLogo.geometry} castShadow receiveShadow>
                <meshStandardMaterial color="red" />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/degenboxLogo.glb')
