/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/degenBox_box.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function DegenBoxModel(props) {
  const { nodes } = useGLTF('/models/degenBox_box.glb')
  const boxTexture = useTexture('/images/degenBox_box_1k.png')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box_Material001_0.geometry} castShadow receiveShadow>
        <meshStandardMaterial map={boxTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/degenBox_box.glb')
