/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Floor.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Floor(props) {
    const { nodes, materials } = useGLTF('/models/Floor.glb')
    const floorMap = useTexture('/images/Floor_Bake1_CyclesBake_COMBINED.png')

    useEffect(() => {
        floorMap.flipY = false
        floorMap.needsUpdate = true
    }, [floorMap])
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Floor_Baked.geometry} receiveShadow>
                <meshStandardMaterial map={floorMap} />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/Floor.glb')
