/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Floor.glb
*/

import React, { useMemo } from 'react'
import { useGLTF, useKTX2 } from '@react-three/drei'

export function Floor(props) {
    const { nodes, materials } = useGLTF('/models/Floor.glb')
    const floorMapRaw = useKTX2('/images/ktx2/Floor_Bake1_CyclesBake_COMBINED.ktx2')

    // KTX2 textures need flipY = false for GLTF models - clone to avoid mutating hook values
    const floorMap = useMemo(() => {
        const t = floorMapRaw.clone()
        t.flipY = false
        t.needsUpdate = true
        return t
    }, [floorMapRaw])

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Floor_Baked.geometry} receiveShadow>
                <meshStandardMaterial map={floorMap} />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/Floor.glb')
