/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vendingMachine.glb
*/

import React, { useMemo, useEffect } from 'react'
import { useGLTF, useKTX2, useTexture } from '@react-three/drei'

export function VendingMachine(props) {
  const { nodes, materials } = useGLTF('/models/vendingMachine.glb')

  {/*const bevMapRaw = useKTX2('/images/ktx2/beverages_Bake1_CyclesBake_COMBINED.ktx2')
  const bodyMapRaw = useKTX2('/images/ktx2/vm_body_Bake1_CyclesBake_COMBINED.ktx2')
  const adsMapRaw = useKTX2('/images/ktx2/vm_ads_Bake1_CyclesBake_COMBINED.ktx2')
  const partsMapRaw = useKTX2('/images/ktx2/vm_parts_Bake1_CyclesBake_COMBINED.ktx2')

  // KTX2 textures need flipY = false for GLTF models - clone to avoid mutating hook values
  const bevMap = useMemo(() => { const t = bevMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [bevMapRaw])
  const bodyMap = useMemo(() => { const t = bodyMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [bodyMapRaw])
  const adsMap = useMemo(() => { const t = adsMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [adsMapRaw])
  const partsMap = useMemo(() => { const t = partsMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [partsMapRaw]) */}

  const bevMap = useTexture('/images/beverages_Bake1_CyclesBake_COMBINED.png')
  const bodyMap = useTexture('/images/vm_body_Bake1_CyclesBake_COMBINED.png')
  const adsMap = useTexture('/images/vm_ads_Bake1_CyclesBake_COMBINED.png')
  const partsMap = useTexture('/images/vm_parts_Bake1_CyclesBake_COMBINED.png')
  
  useEffect(() => {
    bevMap.flipY = false
    bodyMap.flipY = false
    adsMap.flipY = false
    partsMap.flipY = false
    bevMap.needsUpdate = true
    bodyMap.needsUpdate = true
    adsMap.needsUpdate = true
    partsMap.needsUpdate = true
  }, [bevMap, bodyMap, adsMap, partsMap])
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.beverages_Baked.geometry} material={materials.beverages_Baked} >
        <meshStandardMaterial map={bevMap} />
        </mesh>
      <mesh geometry={nodes.vm_ads_Baked.geometry} material={materials.vm_ads_Baked} >
        <meshStandardMaterial map={adsMap} />
      </mesh>
      <mesh geometry={nodes.vm_body_Baked.geometry} material={materials.vm_body_Baked} >
        <meshStandardMaterial map={bodyMap} />
      </mesh>
      <mesh geometry={nodes.vm_parts_Baked.geometry} material={materials.vm_parts_Baked} >
        <meshStandardMaterial map={partsMap} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/vendingMachine.glb')
