/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vendingMachine.glb
*/

import React, { useMemo } from 'react'
import { useGLTF, useKTX2 } from '@react-three/drei'

export function VendingMachine(props) {
  const { nodes, materials } = useGLTF('/models/vendingMachine_hole.glb')

  const bevMapRaw = useKTX2('/images/ktx2/beverages_Bake1_CyclesBake_COMBINED.ktx2')
  const bodyMapRaw = useKTX2('/images/ktx2/vm_body_Bake1_CyclesBake_COMBINED.ktx2')
  const adsMapRaw = useKTX2('/images/ktx2/vm_ads_Bake1_CyclesBake_COMBINED.ktx2')
  const partsMapRaw = useKTX2('/images/ktx2/vm_parts_Bake1_CyclesBake_COMBINED.ktx2')

  // KTX2 textures need flipY = false for GLTF models - clone to avoid mutating hook values
  const bevMap = useMemo(() => { const t = bevMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [bevMapRaw])
  const bodyMap = useMemo(() => { const t = bodyMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [bodyMapRaw])
  const adsMap = useMemo(() => { const t = adsMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [adsMapRaw])
  const partsMap = useMemo(() => { const t = partsMapRaw.clone(); t.flipY = false; t.needsUpdate = true; return t }, [partsMapRaw])
  
  
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.beverages_Baked.geometry} material={materials.beverages_Baked} castShadow receiveShadow>
        <meshStandardMaterial map={bevMap} />
        </mesh>
      <mesh geometry={nodes.vm_ads_Baked.geometry} material={materials.vm_ads_Baked} castShadow receiveShadow>
        <meshStandardMaterial map={adsMap} />
      </mesh>
      <mesh geometry={nodes.vm_body_Baked.geometry} material={materials.vm_body_Baked} castShadow receiveShadow>
        <meshStandardMaterial map={bodyMap} />
      </mesh>
      <mesh geometry={nodes.vm_parts_Baked.geometry} material={materials.vm_parts_Baked} castShadow receiveShadow>
        <meshStandardMaterial map={partsMap} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/vendingMachine_hole.glb')
